In [10]:
print(np.linspace(0,10,num=5))

[ 0.   2.5  5.   7.5 10. ]


In [2]:
import numpy as np

In [11]:
print(np.linspace(0,10,num=4))

[ 0.          3.33333333  6.66666667 10.        ]


In [14]:
# so linspace divide a range of numbers in no of pieces you want


In [15]:
# now to could explicitly tell which datatype you wants to use by default it is floot

In [12]:
x=np.ones(2,dtype=np.int64)

In [13]:
x

array([1, 1])

In [17]:
# NOW ADDING AND SORTING THE ELEMNETS
# np.sort() np.concatenate()

In [18]:
arr=np.array([2,1,5,6,9,3,12,54])


In [19]:
np.sort(arr)

array([ 1,  2,  3,  5,  6,  9, 12, 54])

In [ ]:
# thats how you sort the array and you could use diff types of sorting algo to read more go into the documenation of numpy

In [20]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10,11])

In [22]:
np.concatenate((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [23]:
# and thats how you concatenate an array 

In [24]:
# now what if you start with this kind of array

In [48]:
x=np.array([[1,3,2],[4,3,4]])
y=np.array([[10,11,89]])


In [27]:
# now you gotta add dtype=object at the end of an multi dimensional array or it wont work WHY=? IDK BRO

In [58]:
print(np.concatenate((x,y),axis=0))

[[ 1  3  2]
 [ 4  3  4]
 [10 11 89]]


In [51]:
# okie all the array size should be of the same size COOL!

In [63]:
# now about that axis shit

In [82]:
x=np.array([[1,3]])
y=np.array([[10,11],[4,3]])

In [85]:
print(np.concatenate((x,y.T),axis=1))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 2

In [83]:
print(np.concatenate((y,x.T),axis=1))

[[10 11  1]
 [ 4  3  3]]


In [ ]:
# NOW Thats what axis do default is 0 and you gotta add that .T and that T stands for Transpose

In [ ]:
# And the transpose comes in front of that array which is imean kinda alone just figure it out by looking above example

In [84]:
print(np.concatenate((x,y),axis=0))

[[ 1  3]
 [10 11]
 [ 4  3]]


In [87]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])

In [102]:
simple=np.concatenate((a,b))

In [101]:
with_T=np.concatenate((a,b)).T

In [104]:
print(simple)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [107]:
print(with_T)

[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]


In [108]:
# OK so this hi how matrix concatenation works in numpy and this is how to use .T to transpose the matrix COOL!!

In [109]:
# HOW DO YOU KNOW THE SHAPE AND SIZE OF AN ARRAY

In [110]:
# ndarray.ndim,ndarray.size,ndarray.shapea THESE ARE THE THINGS THAT WE ARE GONNA USE

In [116]:
array_Example=np.array([[[0,1,2,3],[4,5,6,7]],
                     [[0,1,2,3],[4,5,6,7]],
                     [[0,1,2,3],[4,5,6,7]]])

In [114]:
# To find the no of dimensions of the array 

In [118]:
array_Example.ndim

3

In [120]:
# and ndim stands for number of dimensions COOL !! COOL

In [121]:
# now to find number of elements in an array

In [122]:
array_Example.size

24

In [123]:
# now to find the shape of the array

In [124]:
array_Example.shape

(3, 2, 4)

In [125]:
# THATS A FUCKING 3D MATRIX 3 ON THE X 2 ON THE Y AND 4 ON THE Z COOL!! RIGHT

In [126]:
# Now how to reshape an array command arr.reshape()

In [127]:
a=np.arange(6)

In [128]:
print(a)

[0 1 2 3 4 5]


In [129]:
a_arr=a.reshape(2,3)

In [130]:
print(a_arr)

[[0 1 2]
 [3 4 5]]


In [131]:
# Thats how you reshape an array

In [132]:
# NOW HOW TO CONVERT A 2D ARRAY INTO 3D ARRAY 

In [ ]:
# commands :- np.newaxis,np.expand_dims